### ISSUE TITLE
Seems to be depreceated.

### ISSUE THREAD

**Issue by blumerique** [Carcraftz/discord.js-patched-v11#4]
I suddenly got a DiscordAPI Error using the library to create/send embeds. Was working a few hours ago.

UnhandledPromiseRejectionWarning: DiscordAPIError

at /app/node_modules/discord.js-selfbot-v11/src/client/rest/RequestHandlers/Sequential.js:85:15
at /app/node_modules/snekfetch/src/index.js:215:21
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by B1T2** [comment]
Yep. I'm having the same issue. Please take a look into it. Thanks.

**Comment by Carcraftz** [comment]
Bit busy recently so can't look into this myself. If anyone figures this out feel free to submit a PR

**Comment by hackermondev** [comment]
You can't send embeds on normal accounts anymore.
